ibge:
  api:
    url: https://servicodados.ibge.gov.br/api/v1
correios:
  api:
    url: https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente
    soapAction: http://cliente.bean.master.sigep.bsb.correios.com.br/AtendeCliente/consultaCEP

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true